---
- name: Restart MySQL
  service:
    name: mysql
    state: restarted

- name: Stop Apache2
  service:
    name: apache2
    state: stopped

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Restart PHP7-FPM
  service:
    name: php7.4-fpm
    state: restarted